name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 26
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '26'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: auth-service

      - name: Build with Gradle
        # Флаг -Porg.gradle.java.toolchain.accommodate=false заставляет Gradle 
        # не искать тулчейны по системе, а взять системную JAVA_HOME, которую выставил setup-java
        run: ./gradlew build -x test -Porg.gradle.java.toolchain.accommodate=false
        working-directory: auth-service

      - name: Build Docker Image
        run: docker build -t my-docker-username/auth-service:latest .
        working-directory: auth-service
